version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
  pre_build:
    commands:
      - echo "Starting build"
  build:
    commands:
      - git clone https://github.com/jmuachifi/simple-app.git
      - cd simple-app
      - cp * /var/www/html/
  post_build:
    commands:
      - echo "Build completed"
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
      
     
